---

- name: Cisco show version example
  hosts: cisco
  gather_facts: false
  connection: network_cli

  tasks:
    - name: gather all fact
      ios_facts:
      register: facts_output
    
    - name: print fact
      debug:
        var: facts_output

    - copy: content="{{ facts_output | to_nice_json }}" dest="out/{{inventory_hostname}}_iosfacts.json"    
      